name: Build package
on:
  workflow_dispatch:
jobs:
  build_source:
    name: build
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
      - name: List files
        run: ls -R
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: upload package
        uses: actions/upload-artifact@v2
        with:
          name: bundle.zip
          path: ./bundle.zip
