name: Deploy package
on:
  workflow_dispatch:

jobs:
  deploy_package:
    name: Download and deploy lambda to production
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      
    - name: Display structure of downloaded files
      run: ls -R   
       
    - name: zip
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./bundle.zip ./   
    - name: default deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: eu-west-1
        function_name: prd-HelloWorld
        zip_file: bundle.zip
